---
settings:
  name: NetApp Disaster Recovery
  internal:
    pdf_enabled: true
    termcheck_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentación de recuperación ante desastres de NetApp
    url: "/index.html"
  - section: release-notes
  - section: get-started
  - section: use
  - section: reference
  - title: Preguntas frecuentes
    url: "/get-started/dr-faq.html"
  - section: support
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: NetApp Data Services
  repo: data-services-family
