= Retención de la jerarquía de carpetas
:allow-uri-read: 




=== Retención de la jerarquía de carpetas

De forma predeterminada, Disaster Recovery conserva la jerarquía del inventario de VM (estructura de carpetas) en caso de conmutación por error.  Si el destino de recuperación no tiene la carpeta requerida, Disaster Recovery la crea.

Ahora puede anular esta configuración designando una nueva carpeta de VM principal o desmarcando la opción **Conservar jerarquía de carpetas original**.

Para obtener más información, consulte link:../use/drplan-create.adoc["Crear un plan de replicación"].



=== Actualización optimizada del agente de consola

La recuperación ante desastres ahora admite un proceso optimizado para utilizar múltiples agentes de consola en un entorno de trabajo.  Para cambiar entre agentes de consola, debe editar la configuración de vCenter, redescubrir las credenciales y actualizar los planes de replicación para usar el nuevo agente de consola.

Para obtener más información, consulte link:../reference/switch-console-agent.html["Agentes de la consola Switch"].
