---
sidebar: sidebar 
permalink: reference/dr-reference-roles.html 
keywords: how bluexp disaster recovery works, what is disaster recovery, bluexp, vmware, vcenter, draas, replicate, failover, failback, fail over, fail back, vmware cloud, netapp intelligent services 
summary: NetApp Disaster Recovery emplea roles para gobernar el acceso que tiene cada usuario a funciones y acciones específicas. 
---
= Acceso a funciones basado en roles de NetApp Disaster Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use


[role="lead"]
NetApp Disaster Recovery emplea roles para gobernar el acceso que tiene cada usuario a funciones y acciones específicas.

El servicio utiliza los siguientes roles que son específicos de NetApp Disaster Recovery.

* *Administrador de recuperación ante desastres*: realiza cualquier acción en NetApp Disaster Recovery.
* *Administrador de conmutación por error de recuperación ante desastres*: realiza acciones de conmutación por error y migración en NetApp Disaster Recovery.
* *Administrador de aplicaciones de recuperación ante desastres*: crear y modificar planes de replicación e iniciar conmutaciones por error de prueba.
* *Visor de recuperación ante desastres*: ve información en NetApp Disaster Recovery, pero no puede realizar ninguna acción.


Estos roles son específicos de NetApp Disaster Recovery y no son los mismos que los roles de plataforma que se utilizan en la NetApp Console.  Para obtener detalles sobre todas las funciones de la plataforma NetApp Console , consulte https://docs.netapp.com/us-en/bluexp-setup-admin/reference-iam-predefined-roles.html["la documentación de configuración y administración de la NetApp Console"^] .

La siguiente tabla indica las acciones que puede realizar cada rol de NetApp Disaster Recovery .

[cols="30,20a,20a,20a,20a"]
|===
| Característica y acción | Administración de recuperación ante desastres | Administrador de conmutación por error de recuperación ante desastres | Administrador de aplicaciones de recuperación ante desastres | Visor de recuperación ante desastres 


| Ver el panel y todas las pestañas  a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí



| Comience una prueba gratuita  a| 
Sí
 a| 
No
 a| 
No
 a| 
No



| Iniciar el descubrimiento de cargas de trabajo  a| 
Sí
 a| 
No
 a| 
No
 a| 
No



| Ver información de la licencia  a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí



| Activar licencia  a| 
Sí
 a| 
No
 a| 
Sí
 a| 
No



5+| *En la opción Sitios*: 


| Ver sitios  a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí



| Agregar, modificar o eliminar sitios  a| 
Sí
 a| 
No
 a| 
No
 a| 
No



5+| *En la opción Planes de replicación*: 


| Ver planes de replicación  a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí



| Ver detalles del plan de replicación  a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí



| Crear o modificar planes de replicación  a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
No



| Crear informes  a| 
Sí
 a| 
No
 a| 
No
 a| 
No



| Ver instantáneas  a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí



| Realizar pruebas de conmutación por error  a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
No



| Realizar conmutaciones por error  a| 
Sí
 a| 
Sí
 a| 
No
 a| 
No



| Realizar conmutaciones por recuperación  a| 
Sí
 a| 
Sí
 a| 
No
 a| 
No



| Realizar migraciones  a| 
Sí
 a| 
Sí
 a| 
No
 a| 
No



5+| *En la opción Grupos de recursos*: 


| Ver grupos de recursos  a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
Sí



| Crear, modificar o eliminar grupos de recursos  a| 
Sí
 a| 
No
 a| 
Sí
 a| 
No



5+| *Opción de Monitoreo en el Trabajo*: 


| Ver trabajos  a| 
Sí
 a| 
No
 a| 
Sí
 a| 
Sí



| Cancelar trabajos  a| 
Sí
 a| 
Sí
 a| 
Sí
 a| 
No

|===