---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-introduction.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, netapp, ontap 
summary: Introducción de NetApp Disaster Recovery mediante Amazon EVS y Amazon FSx for NetApp ONTAP. 
---
= Aprende sobre NetApp Disaster Recovery con Amazon Elastic VMware Service y Amazon FSx for NetApp ONTAP
:allow-uri-read: 


[role="lead"]
NetApp Disaster Recovery ayuda a proteger las cargas de trabajo de VMware replicando datos desde entornos locales a Amazon EVS y Amazon FSx for NetApp ONTAP para recuperación ante desastres.

Uno de los principales desafíos de cualquier solución de recuperación ante desastres es administrar el costo incremental de comprar, configurar y mantener recursos de computación, red y almacenamiento adicionales solo para brindar una infraestructura de replicación y recuperación de recuperación ante desastres.  Una opción popular para proteger recursos virtuales críticos locales es utilizar recursos virtuales alojados en la nube como infraestructura de replicación y recuperación ante desastres.  Amazon es un ejemplo de una solución que puede proporcionar recursos rentables que son compatibles con las infraestructuras de máquinas virtuales alojadas en NetApp ONTAP .

Amazon ha presentado su servicio Amazon Elastic VMware Service (Amazon EVS), que permite utilizar VMware Cloud Foundation dentro de tu nube privada virtual (VPC). Amazon EVS ofrece la resiliencia y el rendimiento de AWS, junto con el software y las herramientas habituales de VMware, lo que permite que Amazon EVS vCenters se integre con tu infraestructura virtualizada local.

Aunque Amazon EVS incluye recursos de almacenamiento, el uso de almacenamiento nativo puede reducir su eficacia en organizaciones con cargas de trabajo que requieren mucho almacenamiento. En estos casos, combinar Amazon EVS con Amazon FSx for NetApp ONTAP storage (Amazon FSxN) puede ofrecer una solución de almacenamiento más flexible. Además, cuando usas soluciones de almacenamiento NetApp ONTAP en las instalaciones para alojar tu infraestructura VMware, usar Amazon EVS con FSx for ONTAP proporciona interoperabilidad de datos y funciones de protección tanto en entornos locales como en la nube.

Para obtener información sobre Amazon FSx for NetApp ONTAP, consulte https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Introducción a Amazon FSx for NetApp ONTAP"^] .
