---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-closing.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: Introducción de NetApp Disaster Recovery mediante Amazon EVS y Amazon FSxN. 
---
= Conclusión
:allow-uri-read: 


[role="lead"]
NetApp Disaster Recovery ofrece una solución de recuperación ante desastres en nube híbrida y rentable para su infraestructura VMware local cuando se configura para usar Amazon EVS y Amazon FSx for NetApp ONTAP como destino de recuperación ante desastres.  Esto le proporciona un objetivo de recuperación ante desastres sólido para infraestructura de misión crítica.  NetApp Disaster Recovery aprovecha las funciones de protección de datos nativas de ONTAP , respaldadas por décadas de experiencia en protección de datos que se han probado exhaustivamente para garantizar que sus datos estén completamente protegidos.

Para más información:

* https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started.html["Introducción a Amazon FSx for NetApp ONTAP"^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/index.html["Documentación de recuperación ante desastres de NetApp"]

