---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-config-prereqs.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: Debe asegurarse de que se cumplan varios requisitos previos antes de continuar configurando Amazon EVS con NetApp Disaster Recovery. 
---
= Requisitos previos para Amazon EVS con NetApp Disaster Recovery
:allow-uri-read: 


[role="lead"]
Asegúrate de revisar y cumplir los requisitos para configurar Amazon EVS con NetApp Disaster Recovery.

.Prerrequisitos
* Revisa la link:../get-started/dr-prerequisites["requisitos generales para Disaster Recovery"].
* Cree una cuenta de usuario de vCenter con los privilegios específicos de VMware necesarios para que NetApp Disaster Recovery realice las operaciones necesarias.
+

NOTE: Se recomienda que **no** uses la cuenta de administrador predeterminada "\administrator@vsphere.com". En su lugar, deberías crear una cuenta de usuario específica para NetApp Disaster Recovery en todos los clústeres de vCenter que participarán en el proceso de recuperación ante desastres. Para ver una lista de los privilegios específicos requeridos, consulta link:vcenter-privileges.html["Privilegios de vCenter necesarios para NetApp Disaster Recovery"].

* Asegúrate de que todos los almacenes de datos de vCenter que van a alojar máquinas virtuales protegidas por Disaster Recovery estén ubicados en recursos de almacenamiento de NetApp ONTAP.
+
Disaster Recovery es compatible con NFS y VMFS en iSCSI (y no FC) cuando usas Amazon FSx en NetApp ONTAP. Aunque Disaster Recovery es compatible con FC, Amazon FSx for NetApp ONTAP no lo es.

* Asegúrate de que tu Amazon EVS vCenter está conectado a un clúster de almacenamiento Amazon FSx for NetApp ONTAP.
* Asegúrate de que las herramientas de VMware están instaladas en todas las máquinas virtuales protegidas.
* Asegúrate de que tu red local esté conectada a tu red de AWS VPC usando un método de conexión aprobado por Amazon. Se recomienda que uses AWS Direct Connect, AWS Private Link o una VPN de sitio a sitio de AWS.
* Revisa y asegúrate de cumplir con los requisitos de conexión y puerto para EVS con Disaster Recovery:
+
[cols="4"]
|===
| Fuente | Destino | Puerto | Detalles 


| Amazon FSxN | ONTAP on-premises | TCP 11104, 11105, ICMP | SnapMirror 


| ONTAP on-premises | Amazon FSxN | TCP 11104, 11105, ICMP | SnapMirror 


| Agente de NetApp Console | ONTAP on-premises | TCP 443, solo ICMP | Llamadas API 


| Agente de NetApp Console | Amazon FSxN | TCP 441, solo ICMP | Llamadas API 


| Agente de NetApp Console | vCenter (on-premises, EVS), host ESXi (on-premises, EVS) | 443 | Llamadas API, ejecución de scripts 
|===

