---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-config-prereqs.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: Debe asegurarse de que se cumplan varios requisitos previos antes de continuar configurando Amazon EVS con NetApp Disaster Recovery. 
---
= Requisitos previos para Amazon EVS con NetApp Disaster Recovery
:allow-uri-read: 


[role="lead"]
Debe asegurarse de que se cumplan varios requisitos previos antes de continuar configurando Amazon EVS con NetApp Disaster Recovery.

En concreto, haga lo siguiente:

* Cree una cuenta de usuario de vCenter con los privilegios específicos de VMware necesarios para que NetApp Disaster Recovery realice las operaciones necesarias.
+

NOTE: No recomendamos utilizar la cuenta de administrador predeterminada "\administrator@vsphere.com".  En su lugar, debe crear una cuenta de usuario específica de NetApp Disaster Recovery en todos los clústeres de vCenter que participarán en el proceso de recuperación ante desastres.  Para obtener una lista de los privilegios específicos requeridos, consultelink:vcenter-privileges.html["Privilegios de vCenter necesarios para NetApp Disaster Recovery"] .

* Asegúrese de que todos los almacenes de datos de vCenter que alojarán máquinas virtuales protegidas por NetApp Disaster Recovery estén ubicados en recursos de almacenamiento de NetApp ONTAP .
+
El servicio admite NFS y VMFS en iSCSI (y no FC) cuando se utiliza Amazon FSx en NetApp ONTAP.  Si bien el servicio admite FC, Amazon FSx for NetApp ONTAP no lo hace.

* Asegúrese de que su Amazon EVS vCenter esté conectado a un clúster de almacenamiento Amazon FSx for NetApp ONTAP .
* Asegúrese de que las herramientas de VMware estén instaladas en todas las máquinas virtuales protegidas.
* Asegúrese de que su red local esté conectada a su red AWS VPC mediante un método de conexión aprobado por Amazon.  Le recomendamos que utilice AWS Direct Connect, AWS Private Link o una VPN de sitio a sitio de AWS.

