---
sidebar: sidebar 
permalink: reference/evs-deploy-guide-install-connector.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter 
summary: El agente de NetApp Console orquesta la conexión y la gestión entre NetApp Console y los recursos de almacenamiento en la nube o en las instalaciones. 
---
= Instalar el agente de la NetApp Console para NetApp Disaster Recovery
:allow-uri-read: 


[role="lead"]
Un agente de NetApp Console te permite conectar tus implementaciones de NetApp Console a tu infraestructura para orquestar soluciones de forma segura en entornos de AWS, Azure, Google Cloud o locales. El agente de Console ejecuta las acciones que NetApp Console necesita realizar para gestionar tu infraestructura de datos. El agente de Console sondea constantemente la capa de software como servicio de NetApp Disaster Recovery para cualquier acción que necesite realizar.

Para NetApp Disaster Recovery, las acciones que se realizan orquestan clústeres de VMware vCenter e instancias de almacenamiento ONTAP usando API nativas para cada servicio respectivo para proporcionar protección a las máquinas virtuales de producción que se ejecutan en una ubicación local. Aunque el agente de la Console se puede instalar en cualquiera de tus ubicaciones de red, se recomienda que instales el agente de la Console en el sitio de recuperación ante desastres para NetApp Disaster Recovery. Instalarlo en el sitio de recuperación ante desastres asegura que, en caso de una falla del sitio principal, la interfaz de usuario de la NetApp Console mantenga su conexión con el agente de la Console y pueda orquestar el proceso de recuperación dentro de ese sitio de recuperación ante desastres.



== Instalación

* Para usar Disaster Recovery, instala el agente de Console en modo estándar. Para saber más sobre los tipos de instalación del agente de Console, visita https://docs.netapp.com/us-en/console-setup-admin/concept-modes.html["Conoce los modos de implementación de NetApp Console"^].


Los pasos de instalación específicos para el agente de la Console dependen de tu tipo de implementación. Consulta link:https://docs.netapp.com/us-en/console-setup-admin/concept-agents.html["Obtenga más información sobre los agentes de consola"^] para más información.


TIP: El método más sencillo para instalar el agente de la Console con Amazon AWS es usar AWS Marketplace. Para detalles sobre la instalación del agente de la Console usando AWS Marketplace, consulta https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-aws-marketplace.html["Crear un agente de Console desde AWS Marketplace"^].
