---
sidebar: sidebar 
permalink: use/monitor-jobs.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, monitor, bluexp 
summary: NetApp Disaster Recovery es un servicio de recuperación ante desastres basado en la nube que automatiza los flujos de trabajo de recuperación ante desastres.  Puede supervisar todos los trabajos de recuperación ante desastres y determinar su progreso. 
---
= Supervisar trabajos de NetApp Disaster Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Puede supervisar todos los trabajos de NetApp Disaster Recovery y determinar su progreso.



== Ver trabajos

*Rol requerido de NetApp Console* Se requiere el rol de Super admin, Disaster recovery admin, Disaster recovery application admin o Disaster recovery viewer para realizar esta tarea. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["Obtenga información sobre los roles y permisos de usuario en NetApp Disaster Recovery"^]. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^].

.Pasos
. Iniciar sesión en el https://console.netapp.com/["NetApp Console"^] .
. Desde el panel de navegación izquierdo de la NetApp Console , seleccione *Protección* > *Recuperación ante desastres*.
. Desde el menú, seleccione *Supervisión de trabajos*.
. Explora todos los trabajos relacionados con operaciones y revisa sus marcas de tiempo y estado.
. Para ver los detalles de un trabajo en particular, seleccione esa fila.
. Para actualizar la información, seleccione *Actualizar*.




== Cancelar un trabajo

Puedes cancelar un trabajo que está en curso o en estado de cola si se queda atascado o para dar prioridad a una operación pendiente.

*Función de NetApp Console requerida* Para realizar esta tarea se requiere la función Super admin, Disaster recovery admin, Disaster recovery failover admin o Disaster recovery application admin. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["Obtenga información sobre los roles y permisos de usuario en NetApp Disaster Recovery"^]. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^].

.Pasos
. Desde la barra de navegación izquierda de la NetApp Console , seleccione *Protección* > *Recuperación ante desastres*.
. Desde el menú, seleccione *Supervisión de trabajos*.
. En la página del Monitor de trabajos, anote el ID del trabajo que desea cancelar.
+
El trabajo debe estar en estado "En progreso" o "En cola".

. En la columna Acciones, seleccione *Cancelar trabajo*.

