---
sidebar: sidebar 
permalink: use/monitor-jobs.html 
keywords: disaster recovery, bluexp disaster recovery, failover, failback, replicate, fail over, fail back, vmware, vcenter, monitor, bluexp 
summary: NetApp Disaster Recovery es un servicio de recuperación ante desastres basado en la nube que automatiza los flujos de trabajo de recuperación ante desastres.  Puede supervisar todos los trabajos de recuperación ante desastres y determinar su progreso. 
---
= Supervisar trabajos de NetApp Disaster Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/use/


[role="lead"]
Supervisa los trabajos de NetApp Disaster Recovery para hacer un seguimiento de su estado y progreso.



[[view-jobs]]
== Ver trabajos

*Rol requerido de NetApp Console* Se requiere el rol de Super admin, Disaster recovery admin, Disaster recovery application admin o Disaster recovery viewer para realizar esta tarea. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["Obtenga información sobre los roles y permisos de usuario en NetApp Disaster Recovery"^]. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^].

.Pasos
. Iniciar sesión en el https://console.netapp.com/["NetApp Console"^] .
. Desde el panel de navegación izquierdo de la NetApp Console , seleccione *Protección* > *Recuperación ante desastres*.
. Desde el menú, seleccione *Supervisión de trabajos*.
. Revisa los trabajos, incluyendo sus marcas de tiempo y estado.
. Para ver los detalles de un trabajo, selecciona su fila. Para descargar los detalles de un trabajo para revisarlos sin conexión, selecciona el menú de acciones y luego selecciona **Descargar detalles del trabajo**.
+

TIP: Al consultar los detalles de un trabajo, Disaster Recovery muestra el usuario que inició el trabajo. Si el responsable que aparece es «system», Disaster Recovery inició el trabajo.

. Para actualizar la información, seleccione *Actualizar*.




[[cancel-a-job]]
== Cancelar un trabajo

Puedes cancelar un trabajo que está en curso o en estado de cola si se queda atascado o para dar prioridad a una operación pendiente.

*Función de NetApp Console requerida* Para realizar esta tarea se requiere la función Super admin, Disaster recovery admin, Disaster recovery failover admin o Disaster recovery application admin. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["Obtenga información sobre los roles y permisos de usuario en NetApp Disaster Recovery"^]. link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html["Obtenga información sobre los roles de acceso a la NetApp Console para todos los servicios"^].

.Pasos
. Desde la barra de navegación izquierda de la NetApp Console , seleccione *Protección* > *Recuperación ante desastres*.
. Desde el menú, seleccione *Supervisión de trabajos*.
. En la página de seguimiento de trabajos, anota el ID del trabajo que deseas cancelar.
+
El trabajo debe estar en estado "En progreso" o "En cola".

. Selecciona el menú de acciones y luego **Cancelar tarea**.

