---
sidebar: sidebar 
permalink: get-started/dr-prerequisites.html 
keywords: what are disaster recovery requirements, disaster recovery prerequisites, bluexp, disaster recovery 
summary: Antes de utilizar NetApp Disaster Recovery, asegúrese de que su entorno cumpla con los requisitos de almacenamiento ONTAP , clúster VMware vCenter y NetApp Console . 
---
= Requisitos previos de NetApp Disaster Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Antes de utilizar NetApp Disaster Recovery, asegúrese de que su entorno cumpla con los requisitos de almacenamiento ONTAP , clúster VMware vCenter y NetApp Console .



== Versiones de software

[cols="35,55a"]
|===
| Componente | Versión mínima 


| Amazon FSx for NetApp ONTAP  a| 
Última versión disponible



| Google Cloud VMware Engine con Google Cloud NetApp Volumes  a| 
Última versión disponible



| Software ONTAP  a| 
ONTAP 9.10.0 o posterior



| VMware Cloud para AWS  a| 
Última versión disponible



| VMware vCenter local  a| 
7.0u3 o posterior

|===


== Requisitos previos y consideraciones de Google Cloud

Con la recuperación ante desastres en Google Cloud VMware Engine mediante Google Cloud NetApp Volumes, asegúrese de configurar los permisos correctos y cumplir con las consideraciones señaladas.

* Comuníquese con el equipo de SRE de Google para incluir en la lista de permitidos lo siguiente:
+
** API de sincronización para transferir instantáneas desde el almacenamiento local a Google Cloud NetApp Volumes.
** el proyecto de Google con el motor VMware para crear, montar y desmontar almacenes de datos.


* Usted debelink:https://docs.google.com/forms/d/1zuaHu437MNpUf8i5oByK-OTLWXcNIg0es9t036riYRc/viewform?edit_requested=true["Presente una solicitud para incluir en la lista de permitidos sus volúmenes de replicación híbrida"^] .
* Tenga en cuenta lalink:https://docs.cloud.google.com/netapp/volumes/docs/quotas["Cuota y límites de Google Cloud NetApp Volumes"^] .
* Solo puede agregar un volumen o almacén de datos a un plan de replicación.
* Revisar ellink:../release-notes/dr-limitations.html#limitations-with-google-cloud-netapp-volumes["limitaciones"] .


**Consideraciones sobre conmutación por error**

* La conmutación por error solo se admite utilizando la última instantánea.  Si es necesario, puede crear una nueva instantánea durante la captura de instantáneas (es decir, la opción de instantánea selectiva debe estar deshabilitada).
* No es posible crear una nueva instantánea después de una conmutación por error.
* No es posible conservar ni conciliar instantáneas después de una conmutación por error.


**Consideraciones sobre la recuperación**

* La recuperación solo es posible con la opción de instantánea selectiva.  No es posible realizar una conmutación por recuperación tomando una nueva instantánea.
* Si elimina el emparejamiento de clústeres entre el almacenamiento local y los clústeres de almacenamiento de Google Cloud NetApp Volumes , debe borrar manualmente la entrada de emparejamiento de clústeres y máquinas virtuales de almacenamiento del clúster local. Para obtener más información, consulte link:https://docs.netapp.com/us-en/ontap-cli/vserver-peer-delete.html["Eliminar una relación de pares vserver"^].




=== Permisos de Google Cloud

Al principal de servicio en Google Cloud se le deben asignar los siguientes roles o permisos equivalentes:

* link:https://docs.cloud.google.com/compute/docs/access/iam["Rol de administrador de cómputo"^]
* link:https://docs.netapp.com/us-en/console-setup-admin/reference-permissions-gcp.html["Permisos de Google Cloud para la NetApp Console"^]
* link:https://docs.cloud.google.com/iam/docs/roles-permissions/netapp["Administrador de Google Cloud NetApp Volumes"]
* link:https://docs.cloud.google.com/vmware-engine/docs/iam#vmware-engine-roles["Administrador de servicios de VMware Engine"^]




=== Permisos de la NetApp Console

El usuario de la NetApp Console debe tener los siguientes roles:

* link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-gcnv-roles.html["Administrador de Google Cloud NetApp Volumes"^]
* link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-predefined-roles.html#data-service-roles["Administrador de SnapCenter"^]
* link:https://docs.netapp.com/us-en/console-setup-admin/reference-iam-disaster-rec-roles.html["Administrador de conmutación por error de recuperación ante desastres"^]




== Requisitos previos de almacenamiento de ONTAP

Estos requisitos previos se aplican a las instancias de ONTAP o Amazon FSX para NetApp ONTAP .

* Los clústeres de origen y destino deben tener una relación de pares.
* La SVM que aloja los volúmenes de recuperación ante desastres debe existir en el clúster de destino.
* El SVM de origen y el SVM de destino deben tener una relación de pares.
* Si se implementa con Amazon FSx for NetApp ONTAP, se aplica el siguiente requisito previo:
+
** Debe existir una instancia de Amazon FSx for NetApp ONTAP para alojar almacenes de datos de VMware DR en su VPC. Para empezar, consultelink:https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/getting-started-step1.html["Documentación de Amazon FSx para ONTAP"^] .






== Requisitos previos de los clústeres de VMware vCenter

Estos requisitos previos se aplican tanto a los clústeres de vCenter locales como al centro de datos definido por software (SDDC) de VMware Cloud para AWS.

* Revisarlink:../reference/vcenter-privileges.html["Privilegios de vCenter"] requerido para NetApp Disaster Recovery.
* Todos los clústeres de VMware que desea que NetApp Disaster Recovery administre utilizan volúmenes ONTAP para alojar cualquier máquina virtual que desee proteger.
* Todos los almacenes de datos de VMware que administrará NetApp Disaster Recovery deben utilizar uno de los siguientes protocolos:
+
** Sistema Nacional de Archivos
** VMFS utilizando el protocolo iSCSI o FC


* VMware vSphere versión 7.0 Actualización 3 (7.0v3) o posterior
* Si utiliza VMware Cloud SDDC, se aplican estos requisitos previos.
+
** En VMware Cloud Console, utilice los roles de servicio de Administrador y Administrador de NSX Cloud.  Utilice también el propietario de la organización para el rol de Organización. Referirse a https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/vmware-cloud-ontap.html["Uso de VMware Cloud Foundations con AWS FSx para la documentación de NetApp ONTAP"^] .
** Vincule VMware Cloud SDDC con la instancia de Amazon FSx for NetApp ONTAP . Referirse a https://vmc.techzone.vmware.com/fsx-guide#overview["Información sobre la integración de VMware Cloud on AWS con Amazon FSx for NetApp ONTAP"^] .






== Requisitos previos de la NetApp Console



=== Comience a utilizar la NetApp Console

Si aún no lo has hecho, https://docs.netapp.com/us-en/console-setup-admin/task-sign-up-saas.html["Regístrese en la NetApp Console y cree una organización"^] .



=== Recopilar credenciales para ONTAP y VMware

* Las credenciales de Amazon FSx para ONTAP y AWS deben agregarse al sistema dentro del proyecto de la NetApp Console que administra la NetApp Disaster Recovery.
* NetApp Disaster Recovery requiere credenciales de vCenter.  Ingresa las credenciales de vCenter cuando agrega un sitio en NetApp Disaster Recovery.
+
Para obtener una lista de los privilegios de vCenter necesarios, consultelink:../reference/vcenter-privileges.html["Privilegios de vCenter necesarios para NetApp Disaster Recovery"] .  Para obtener instrucciones sobre cómo agregar un sitio, consultelink:../use/sites-add.html["Agregar un sitio"] .





=== Crear el agente de la NetApp Console

El agente de consola es un componente de software que permite que la consola se comunique con su almacenamiento ONTAP y los clústeres VMware vCenter. Es necesario para que la recuperación ante desastres funcione correctamente. El agente reside en su red privada (ya sea un centro de datos local o una VPC en la nube) y se comunica con sus instancias de almacenamiento ONTAP y cualquier componente adicional de servidor y aplicación. Para la recuperación ante desastres, este es el acceso a sus clústeres de vCenter administrados.

Se debe configurar un agente de consola en la NetApp Console.  Cuando utilice el agente, incluirá las capacidades adecuadas para el servicio de recuperación ante desastres.

* NetApp Disaster Recovery solo funciona con la implementación del agente en modo estándar. Ver https://docs.netapp.com/us-en/console-setup-admin/task-quick-start-standard-mode.html["Introducción a la NetApp Console en modo estándar"^] .
* Asegúrese de que tanto el vCenter de origen como el de destino utilicen el mismo agente de consola.
* Tipo de agente de consola necesario:
+
** *Recuperación ante desastres local a local*: instale el agente local de la consola en el sitio de recuperación ante desastres. Con este método, una falla del sitio principal no impide que el servicio reinicie sus recursos virtuales en el sitio de recuperación ante desastres. Referirse a https://docs.netapp.com/us-en/console-setup-admin/task-install-connector-on-prem.html["Instalar y configurar el agente de consola en las instalaciones"^] .
+
La recuperación ante desastres también admite el uso de múltiples agentes de consola con configuraciones locales. Para este escenario, los agentes de la consola dirigen acciones a los vCenters y a los clústeres de matrices ONTAP , y el origen y el destino tendrían cada uno su propio agente de consola. Se recomienda utilizar varios agentes de consola para reducir la latencia y mejorar el tiempo de recuperación si falla un agente de consola o un sitio.

** *En las instalaciones de AWS*: instale el agente de consola para AWS en su VPC de AWS. Referirse a https://docs.netapp.com/us-en/console-setup-admin/concept-install-options-aws.html["Opciones de instalación del agente de consola en AWS"^] .
+

TIP: Para conexiones locales a locales, utilice el agente de consola local.  Para las instalaciones locales en AWS, utilice el agente de la consola de AWS, que tiene acceso al vCenter local de origen y al vCenter local de destino.

** El agente de consola instalado debe poder acceder a cualquier instancia de clúster de VMware vCenter y a los hosts ESXi administrados por esos clústeres de vCenter que gestionará la Recuperación ante Desastres.


* Todas las matrices ONTAP que serán administradas por NetApp Disaster Recovery deben agregarse a cualquier sistema dentro del proyecto de la NetApp Console que se utilizará para administrar NetApp Disaster Recovery.
+
Ver https://docs.netapp.com/us-en/storage-management-ontap-onprem/task-discovering-ontap.html["Descubra los clústeres ONTAP locales"^] .

* Para obtener información sobre cómo configurar un proxy inteligente para NetApp Disaster Recovery, consultelink:../get-started/dr-setup.html["Configure su infraestructura para NetApp Disaster Recovery"] .




== Requisitos previos de la carga de trabajo

Para garantizar que los procesos de coherencia de aplicaciones sean exitosos, aplique estos requisitos previos:

* Asegúrese de que las herramientas de VMware (o las herramientas de OpenVM) se estén ejecutando en las máquinas virtuales que estarán protegidas.
* Para las máquinas virtuales Windows que ejecutan Microsoft SQL Server, Oracle Database o ambos, las bases de datos deben tener habilitados sus escritores VSS.
* Las bases de datos Oracle que se ejecutan en un sistema operativo Linux deben tener habilitada la autenticación de usuario del sistema operativo para el rol SYSDBA de la base de datos Oracle.

