---
sidebar: sidebar 
permalink: get-started/reference-vmware-prerequisites.html 
keywords: vmware cluster prerequisites, vmware, vcenter, requirements 
summary: Antes de usar NetApp Disaster Recovery, asegúrate de que tu entorno cumple los requisitos del clúster de VMware vCenter. 
---
= Requisitos previos del clúster de VMware vCenter para NetApp Disaster Recovery
:hardbreaks:
:allow-uri-read: 
:icons: font
:imagesdir: ../media/get-started/


[role="lead"]
Antes de usar NetApp Disaster Recovery, asegúrate de que tu entorno cumple los requisitos del clúster de VMware vCenter.



[[general-prerequisites]]
== Requisitos generales

Estos requisitos previos se aplican tanto a los clústeres de vCenter locales como al centro de datos definido por software (SDDC) de VMware Cloud para AWS.

* Revisarlink:../reference/vcenter-privileges.html["Privilegios de vCenter"] requerido para NetApp Disaster Recovery.
* Todos los clústeres de VMware que NetApp Disaster Recovery gestiona deben usar volúmenes ONTAP para alojar las máquinas virtuales que quieres proteger.
* Todos los almacenes de datos de VMware que administrará NetApp Disaster Recovery deben utilizar uno de los siguientes protocolos:
+
** Sistema Nacional de Archivos
** VMFS utilizando el protocolo iSCSI o FC


* VMware vSphere versión 7.0 Actualización 3 (7.0v3) o posterior




[[vmware-cloud-sddc-prerequisites]]
== Requisitos previos de VMware Cloud SDDC

Si estás usando VMware Cloud SDDC, se aplican estos requisitos previos adicionales:

* En VMware Cloud Console, utilice los roles de servicio de Administrador y Administrador de NSX Cloud.  Utilice también el propietario de la organización para el rol de Organización. Referirse a https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/vmware-cloud-ontap.html["Uso de VMware Cloud Foundations con AWS FSx para la documentación de NetApp ONTAP"^] .
* Conecta el SDDC de VMware Cloud con una instancia de Amazon FSx para NetApp ONTAP. Consulta https://vmc.techzone.vmware.com/fsx-guide#overview["Información sobre la integración de VMware Cloud on AWS con Amazon FSx for NetApp ONTAP"^].

